"""Advent of Code 2024 - Unit tests for day 8 tasks"""

from src.util import get_lines
from ..day08 import part_one, part_two


example_data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""".split(
    "\n"
)


def test_part_one() -> None:
    """
    Test function for part_one.

    This function tests the implementation of the part_one function by asserting the expected output

    Returns:
        None
    """

    example_data2 = """..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........""".split(
        "\n"
    )
    example_data3 = """.........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
..........""".split(
        "\n"
    )

    assert part_one(example_data2) == 2
    assert part_one(example_data3) == 4
    assert part_one(example_data) == 14
    assert part_one(get_lines("day08")) == 329


def test_part_two() -> None:
    """
    Test function for part_two.

    This function tests the implementation of the part_two function by asserting the expected output

    Returns:
        None
    """

    example_data4 = """T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........""".split(
        "\n"
    )
    assert part_two(example_data4) == 9
    assert part_two(example_data) == 34
    assert part_two(get_lines("day08")) == 1190
